version: '3'

services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: databaseSQL
    environment:
      ACCEPT_EULA: "Y"
      sa_password: "P@55w0rd123"
    ports:
      - "1433:1433"
    volumes:
      - ./.docker/:/var/opt/mssql/data
