version: '3'

services:
  database:
    user: root
    image: mcr.microsoft.com/azure-sql-edge
    container_name: databaseSQL
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@55w0rd123"
    ports:
      - "5431:1431"
      - "5433:1433"
    volumes:
      - ./.docker/database/:/var/opt/mssql/data
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-U",
          "sa",
          "-P",
          "P@55w0rd123",
          "-Q",
          "select 1"
        ]
      interval: 1s
      retries: 5

  app:
    container_name: "app"
    build: .
    ports:
      - "3333:80"
    volumes:
      - ./.docker/app/uploads/:/app/public/uploads
    environment:
      Settings:UploadDataDir: "/app/public/uploads"
      ConnectionStrings:DefaultConnection: "Server=database;Initial Catalog=CloudIn;User Id=sa;Password=P@55w0rd123;"
    depends_on:
      database:
        condition: service_healthy
